export const SEARCH_BY_INGREDIANT = "SEARCH_BY_INGREDIANT";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const SEARCH_BY_INGNAME = "SEARCH_BY_INGNAME";
export const TOGGLE_COCKTIL_STATE = "TOGGLE_COCKTIL_STATE";
export const GET_COCKTAIL = "GET_COCKTAIL";